"""
python create_metadata_files.py /home/najo/NAS/VLA/dataset/New_dataset6/Red_point
python create_metadata_files.py /home/najo/NAS/VLA/dataset/New_dataset6/Green_point
python create_metadata_files.py /home/najo/NAS/VLA/dataset/New_dataset6/Blue_point
python create_metadata_files.py /home/najo/NAS/VLA/dataset/New_dataset6/White_point
python create_metadata_files.py /home/najo/NAS/VLA/dataset/New_dataset6/Yellow_point

"""

import json
import os
from pathlib import Path
import argparse

def create_metadata_for_episode(episode_dir: Path):
    """Creates a metadata.json file for a single episode directory."""
    if not episode_dir.is_dir():
        print(f"Skipping non-directory: {episode_dir}")
        return

    metadata_path = episode_dir / "metadata.json"
    if metadata_path.exists():
        print(f"Metadata already exists for {episode_dir.name}, skipping.")
        return

    # Infer camera views from subdirectories
    camera_views = sorted([d.name for d in episode_dir.iterdir() if d.is_dir() and d.name.startswith("View")])

    if not camera_views:
        print(f"Warning: No 'View*' directories found in {episode_dir.name}. Cannot create metadata.")
        return

    metadata = {
        "robot_hz": 100,
        "sensor_hz": 650,
        "camera_views": camera_views,
        "notes": "Auto-generated by create_metadata_files.py"
    }

    with open(metadata_path, 'w') as f:
        json.dump(metadata, f, indent=4)

    print(f"Created metadata.json for {episode_dir.name}")

def main():
    parser = argparse.ArgumentParser(description="Create metadata.json files for new format datasets.")
    parser.add_argument("dataset_root", type=str, help="Path to the root directory containing task folders (e.g., .../New_dataset4/Eye_trocar).")
    args = parser.parse_args()

    root_path = Path(args.dataset_root)
    if not root_path.exists():
        print(f"Error: Root path not found: {root_path}")
        return

    print(f"Scanning for episodes in {root_path}...")

    episode_dirs = [d for d in root_path.iterdir() if d.is_dir() and d.name.startswith("data_collection_")]

    if not episode_dirs:
        print("No 'data_collection_*' directories found.")
        return

    for episode_dir in episode_dirs:
        create_metadata_for_episode(episode_dir)

    print("\nDone.")

if __name__ == "__main__":
    main()
