python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
python /home/zed_box/NAS/Insertion_VLAv2/Data_collection/Robot_sender.py
sleep 2
